/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.component';
const styles_RootComponent:any[] = ([] as any[]);
export const RenderType_RootComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_RootComponent,data:{}});
export function View_RootComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h2',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['Base App: Root Component']))],(null as any),(null as any));
}
export function View_RootComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_RootComponent_0,RenderType_RootComponent)),
      i0.ɵdid(49152,(null as any),0,i1.RootComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const RootComponentNgFactory:i0.ComponentFactory<i1.RootComponent> = i0.ɵccf('my-app',
    i1.RootComponent,View_RootComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovQXJ1bi5NYW5nbGljay9BcnVuLk1hbmdsaWNrLkFQUkovQXJ1bi5NYW5nbGljay5TeW5lLkFuZ3VsYXIvMDJfQW5ndWxhci9EYXkgMTIvMDhfQU9UL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0FydW4uTWFuZ2xpY2svQXJ1bi5NYW5nbGljay5BUFJKL0FydW4uTWFuZ2xpY2suU3luZS5Bbmd1bGFyLzAyX0FuZ3VsYXIvRGF5IDEyLzA4X0FPVC9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L0FydW4uTWFuZ2xpY2svQXJ1bi5NYW5nbGljay5BUFJKL0FydW4uTWFuZ2xpY2suU3luZS5Bbmd1bGFyLzAyX0FuZ3VsYXIvRGF5IDEyLzA4X0FPVC9hcHAvYXBwLmNvbXBvbmVudC50cy5Sb290Q29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9BcnVuLk1hbmdsaWNrL0FydW4uTWFuZ2xpY2suQVBSSi9BcnVuLk1hbmdsaWNrLlN5bmUuQW5ndWxhci8wMl9Bbmd1bGFyL0RheSAxMi8wOF9BT1QvYXBwL2FwcC5jb21wb25lbnQudHMuUm9vdENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMj5CYXNlIEFwcDogUm9vdCBDb21wb25lbnQ8L2gyPiIsIjxteS1hcHA+PC9teS1hcHA+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBOzs7b0JDQUo7TUFBQTthQUFBOzs7OyJ9
